name: flutter_app
description: A new Flutter project.
version: 1.0.3
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

# 依赖
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  # 国际化
  flutter_localizations:
    sdk: flutter
  # 状态管理
  provider: ^5.0.0
  # 常用工具类库
  flustars: ^2.0.1
  # 屏幕适配工具
  flutter_screenutil: ^5.0.0+2
  # 获取当前设备信息
  device_info: ^2.0.1
  package_info: ^2.0.2
  # 轮播图
  flutter_swiper_null_safety: ^1.0.2
  carousel_slider: ^4.0.0 
  # 网络
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 带缓存的图片
  cached_network_image: ^3.0.0
  # 底部抽屉
  sliding_up_panel: ^2.0.0+1
  #用于做骨架屏-闪光效果
  shimmer: ^2.0.0
  #跳转系统浏览器/打电话等
  url_launcher: ^6.0.6
  # 颜色
  colour: ^1.0.5
  # tabbar google_nav_bar
  custom_navigation_bar: ^0.8.2
  # flutter packages pub run build_runner build
  # flutter packages pub run build_runner watch
  json_annotation: ^4.0.1
  # 动画
  animations: ^2.0.0
  # 瀑布流 StaggeredTile.fit(1) has bug
  flutter_staggered_grid_view: ^0.4.0
  # 瀑布流
  waterfall_flow: ^3.0.1
  # 解决nestedScroll 子控件单独下拉刷新 否则只能在父控件中判定哪个子控件在刷新
  extended_nested_scroll_view: ^3.0.0
  # 视频播放
  chewie: ^1.2.2
  wakelock: 0.5.3+3
  fijkplayer: ^0.10.0
  # 获取图片主色
  palette_generator: ^0.3.0
  # 音频播放
  audioplayers: ^0.19.0
  # 数据库
  sqflite: ^2.0.0+3
  sembast: ^3.1.0+2
  # 播放列表
  modal_bottom_sheet: ^2.0.0
  # 点
  ink_page_indicator: ^0.2.1
  # toast 
  flash: ^2.0.1
  # 按钮
  like_button: ^2.0.2
  # 防抖和节流
  rate_limiter: ^0.1.1
  # 标签
  extended_tabs: ^2.3.0
  draggable_container: ^1.0.7+2
  collection: ^1.15.0
  # 展开控件
  expandable: ^5.0.1
  #  富文本
  extended_text: ^7.0.0
  # 是否可见
  visibility_detector: ^0.2.0
  # 跑马灯
  marquee: ^2.2.0
  # segment
  custom_sliding_segmented_control: ^1.2.1
  # section header
  flutter_sticky_header: ^0.6.0
  # 监听网络
  connectivity_plus: ^1.1.0
  # 跳到指定的位置
  scrollable_positioned_list: ^0.2.0-nullsafety.0 

  
  ### snapping_sheet
  ### https://pub.dev/packages/quds_ui_kit 播放按钮切换动画
  ### https://github.com/kevintonb/neumorph_music_player
  ### 多级tab https://pub.dev/packages/extended_tabs
  ## 菜单编辑 https://juejin.cn/post/6983832427294621733
  ## 主题 https://juejin.cn/post/6981977737560850469#heading-21
  ## 主题 https://github.com/kdsuneraavinash/theme_provider

  ## https://pub.dev/packages/scrollable_list_tabview

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  json_serializable: ^4.1.3
  build_runner: ^2.0.0
  wakelock_platform_interface: 0.2.1+2

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/json/music_home/
    - assets/json/music_search/
    - assets/json/music_comment/
    - assets/json/music_internal/
    - assets/json/music_play_list/
    - assets/json/music_dj/
    - assets/images/
    - assets/images/music/
    # - assets/images/2.0x/
    # - assets/images/3.0x/
  
   # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
  fonts:
    - family: KuaiLe # https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
    
    - family: QyIcon
      fonts:
        - asset: assets/iconfont/iconfont.ttf

flutter_intl:
  enabled: true
